# Generated by Django 2.1.8 on 2019-08-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('birth', models.DateField(null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('intro', models.CharField(default='', max_length=511)),
                ('good_count', models.IntegerField(default=0)),
                ('bad_count', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.PROTECT, to='poll.Subject')),
            ],
            options={
                'db_table': 'tb_teacher',
            },
        ),
    ]
