# Generated by Django 2.1.8 on 2019-08-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190814_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '学科', 'verbose_name_plural': '学科'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '老师', 'verbose_name_plural': '老师'},
        ),
        migrations.AddField(
            model_name='subject',
            name='create_date',
            field=models.DateField(null=True, verbose_name='成立日期'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='intro',
            field=models.CharField(max_length=511, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bad_count',
            field=models.IntegerField(default=0, verbose_name='差评'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth',
            field=models.DateField(null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='good_count',
            field=models.IntegerField(default=0, verbose_name='好评'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='intro',
            field=models.CharField(default='', max_length=511, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=15, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.CharField(max_length=255, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.PROTECT, to='poll.Subject', verbose_name='所属学科'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tel',
            field=models.CharField(max_length=15, null=True, verbose_name='电话'),
        ),
    ]
