# Generated by Django 2.1.8 on 2019-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20190814_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性别'),
        ),
    ]
