# Generated by Django 2.1.8 on 2019-08-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_teacher_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
        ),
    ]
